### ISSUE TITLE
It's there a documentation ?

### ISSUE THREAD

**Issue by hopperhuang** [munrocket/ta-math#26]

**Comment by hopperhuang** [comment]
Oooooop, I think I can use the library alongside reading the unit test. But I suggest that  a detail documentation can be better, more helpful and more easily used.

**Comment by munrocket** [comment]
Ok, I will add it little bit later.

**Comment by hopperhuang** [comment]
> Ok, I will add it little bit later.

Thank you.

**Comment by munrocket** [comment]
Maid a first version as promised https://github.com/munrocket/ta-math/wiki
Still need an improvement.
