### ISSUE TITLE
curious about rsi 

### ISSUE THREAD

**Issue by hopperhuang** [munrocket/ta-math#29]
```
export function rsi($close: Array<number>, window: number) {
  let gains = [0], loss = [1e-14];
  for (let i = 1, len = $close.length; i < len; i++) {
    let diff = $close[i] - $close[i - 1];
    gains.push(diff >= 0 ? diff : 0);
    loss.push(diff < 0 ? -diff : 0);
  }
  return pointwise((a: number, b: number) => 100 - 100 / (1 + a / b), ema(gains, 2 * window - 1), ema(loss, 2 * window - 1));
}
```

1. why use ema here?
2. why should the window be double?

refference :  https://www.macroption.com/rsi-calculation/
i don't think you should double the window.

**Comment by munrocket** [comment]
I am using EMA but trying to create center of mass similar to SMA as described here https://en.m.wikipedia.org/wiki/Moving_average#Relationship_between_SMA_and_EMA. In other words this an internal parameter that define an weight.

**Comment by munrocket** [comment]
Probably I should make it more clear somehow or need to rethink, here ema definition, when we choose `2*window-1`, we get weight=window.
```
export function ema(series: Array<number>, window: number, start ?: number) {
  let weight = 2 / (window + 1);
  let ema = [ start ? start : mean(series.slice(0, window)) ];
  for (let i = 1, len = series.length; i < len; i++) {
    ema.push(series[i] * weight + (1 - weight) * ema[i - 1]);
  }
  return ema;
}
```

**Comment by munrocket** [comment]
Seems you right, it can be a good PR.

**Comment by hopperhuang** [comment]
> Seems you right, it can be a good PR.

Use ema is reasonable, but double the window, is not needed, I think.

PR ? hahaha, I am lazy. And my node version cannot run the unit test. It seems that fix this little problem more quickly by yourself.

Thanks for your quickly replying.

**Comment by munrocket** [comment]
By the way, I will make wiki page today.

**Comment by hopperhuang** [comment]
> By the way, I will make wiki page today.

That's great.

**Comment by hopperhuang** [comment]
> Probably I should make it more clear somehow or need to rethink, here ema definition, when we choose `2*window-1`, we get weight=window.
> 
> ```
> export function ema(series: Array<number>, window: number, start ?: number) {
>   let weight = 2 / (window + 1);
>   let ema = [ start ? start : mean(series.slice(0, window)) ];
>   for (let i = 1, len = series.length; i < len; i++) {
>     ema.push(series[i] * weight + (1 - weight) * ema[i - 1]);
>   }
>   return ema;
> }
> ```


if you double the window, you can the the weight equal to 1 / window, I think this is unreasonable.
And that, will here cause a bug ? if you double the window, more data is needed for slice
```
  let ema = [ start ? start : mean(series.slice(0, window)) ];
``
At last, if you double the window, i wanna get a rsi index in 14 days, but it returns another rsi index calculated by data which use 26 days as a period.

**Comment by munrocket** [comment]
Yep, you can make PR in web, without editor.
Just fork and open this file for edit in your repo, save and than press pull request 😊

**Comment by hopperhuang** [comment]
> Yep, you can make PR in web, without editor.
> Just fork and open this file for edit in your repo, save and than press pull request 😊

I have open a PR about this problem. While you have to fix the unit test by yourself.

**Comment by munrocket** [comment]
Yep, thanks!

**Comment by munrocket** [comment]
Seems that tests not precise enough 😄
