### ISSUE TITLE
implement about Stochastic Oscillator (Full)

### ISSUE THREAD

**Issue by hopperhuang** [munrocket/ta-math#31]
I think the current implement of Stochastic Oscillator (Full) is not right. Instead, it's the implement of  Stochastic Oscillator (Fast)

current algorithm:
```
export function stoch($high: Array<number>, $low: Array<number>,
                      $close: Array<number>, window: number, signal: number, smooth: number) {
  let lowest = rolling((s: Array<number>) => Math.min(...s), $low, window);
  let highest = rolling((s: Array<number>) => Math.max(...s), $high, window);
  let K = pointwise((h: number, l: number, c: number) => 100 * (c - l) / (h - l), highest, lowest, $close); 
  if (smooth > 1) { K = sma(K, smooth) }
  return { line: K, signal: sma(K, signal) };
}
```
Below is the description about difference between fast, slow and full.

Fast Stochastic Oscillator:

Fast %K = %K basic calculation
Fast %D = 3-period SMA of Fast %K
Slow Stochastic Oscillator:

Slow %K = Fast %K smoothed with 3-period SMA
Slow %D = 3-period SMA of Slow %K
The Full Stochastic Oscillator is a fully customizable version of the Slow Stochastic Oscillator. Users can set the look-back period, the number of periods for slow %K and the number of periods for the %D moving average. The default parameters were used in these examples: Fast Stochastic Oscillator (14,3), Slow Stochastic Oscillator (14,3) and Full Stochastic Oscillator (14,3,3).

Full Stochastic Oscillator:

Full %K = Fast %K smoothed with X-period SMA
Full %D = X-period SMA of Full %K

compare with current algorithm, current implement is the fast one.

I recommend  modify current description, change Stochastic Oscillator (Full) to Stochastic Oscillator (Fast). Meanwhile, imply another two indicator.

Reference: [here](https://school.stockcharts.com/doku.php?id=technical_indicators:stochastic_oscillator_fast_slow_and_full)

**Comment by hopperhuang** [comment]
I think slow Stoch should imply like this
```
export function stoch($high: Array<number>, $low: Array<number>,
                      $close: Array<number>, window: number, signal: number, smooth: number) {
  let lowest = rolling((s: Array<number>) => Math.min(...s), sma($low, 3) , window);
  let highest = rolling((s: Array<number>) => Math.max(...s), sma($high, 3), window);
  let K = pointwise((h: number, l: number, c: number) => 100 * (c - l) / (h - l), highest, lowest, $close); 
  return { line: K, signal: sma(K,3) };
}

```

**Comment by munrocket** [comment]
I need to check this.

**Comment by munrocket** [comment]
In the same reference:
```
Full Stochastic Oscillator:

Full %K = Fast %K smoothed with X-period SMA
Full %D = X-period SMA of Full %K
```
But you suggesting to fix X=3, but X should be any natural number [1, 2, 3, ...]

**Comment by hopperhuang** [comment]
> In the same reference:
> 
> ```
> Full Stochastic Oscillator:
> 
> Full %K = Fast %K smoothed with X-period SMA
> Full %D = X-period SMA of Full %K
> ```
> 
> But you suggesting to fix X=3, but X should be any natural number [1, 2, 3, ...]

Yes, My suggestion is for Slow Stoch. Instead for Full Stoch, It should imply like this:
```
export function stoch($high: Array<number>, $low: Array<number>,
                      $close: Array<number>, window: number, period: number) {
  let lowest = rolling((s: Array<number>) => Math.min(...s), sma($low, period) , window);
  let highest = rolling((s: Array<number>) => Math.max(...s), sma($high, period), window);
  let K = pointwise((h: number, l: number, c: number) => 100 * (c - l) / (h - l), highest, lowest, $close); 
  return { line: K, signal: sma(K,period) };
}

```
You can  compare the suggested implement with definition carefully.

**Comment by munrocket** [comment]
Yea, you right. I am curious how better to implement this. Two versions?

**Comment by munrocket** [comment]
I will fix this little bit later with two versions, or you can send PR :)

**Comment by hopperhuang** [comment]
> I will fix this little bit later with two versions, or you can send PR :)

That's great. No PR  here ... hahahaha.

**Comment by munrocket** [comment]
Thanks anyway 🙆
I will fix it.

**Comment by munrocket** [comment]
Fast:
```
%K = (Current Close - Lowest Low)/(Highest High - Lowest Low) * 100
%D = 3-day SMA of %K

Lowest Low = lowest low for the look-back period
Highest High = highest high for the look-back period
%K is multiplied by 100 to move the decimal point two places
```

Slow:
The Slow Stochastic Oscillator smooths %K with a 3-day SMA, **which is exactly what %D is in the Fast Stochastic Oscillator**. Notice that %K in the Slow Stochastic Oscillator equals %D in the Fast Stochastic Oscillator
```
Slow %K = Fast %K smoothed with 3-period SMA
Slow %D = 3-period SMA of Slow %K
```

**Comment by munrocket** [comment]
All is ok here, I will refactor little bit to make it more clear.
