### ISSUE TITLE
RSI calculation appears to be wrong

### ISSUE THREAD

**Issue by LeoAlvarez** [munrocket/ta-math#35]
Comparing to other charting sites (TradingView, Yahoo, StockCharts,etc), values appear to be off by about 10% with the latest fix. 

Reverting back to the previous version fixes most of it, but needs more testing.

**Comment by munrocket** [comment]
@LeoAlvarez so, this was wrong https://github.com/munrocket/ta-math/commit/7efdb0cdc3780762806326a20403ebebedd2345e ?

**Comment by LeoAlvarez** [comment]
Yup, exactly that -- I changed it locally and it worked.

**Comment by munrocket** [comment]
Sorry for delay, I just reverted but need to review it more properly. Fixed for now.
