### ISSUE TITLE
[Proposal] CodeSandbox examples

### ISSUE THREAD

**Issue by IljaDaderko** [munrocket/ta-math#37]
Hey 👋

I came across this lib today and after using it for few calculations, I think it has great potential (I found it very hard to find good ta libs for typescript env, that are also well tested).

It was a bit tricky to get started due to little documentation and I found that example a bit overwhelming as it was doing a lot of stuff related to drawing charts. My use case was simpler, I just want to use this lib to perform ta calculations in NodeJS env and get indicators.

This lead me to idea of how I might be able to help here in terms of contribution, would you be open to following idea?

I want to create a set of small https://codesandbox.io examples for each function that just use small dummy data array and mainly aim to provide good examples of how each function should be used. These examples could than be added to your tables in readme perhaps?

Latter on if I have time I could try to also add charts showcasing each indicator individually, but for time being I just wanted to output indicator values as text on the page.

Let me know what you think, would love to help 👍 will also help me learn the lib better.

**Comment by munrocket** [comment]
I will add your examples in documentation! If you will do it, thanks.
