### ISSUE TITLE
dist/ta-math.d.ts is missing

### ISSUE THREAD

**Issue by MinimogDev** [munrocket/ta-math#39]
I got an error in vscode saying that types are missing. After glancing at package.json they seem to be defined, however it appears that actual `dist/ta-math.d.ts` file does not exist. Never worked with rollup, but I'm pretty sure it is due to `'declaration': false` in rollup config? https://github.com/munrocket/ta-math/blob/master/rollup.config.js#L15

If that's the case, I can make quick PR to change it to `true` 👍

**Comment by munrocket** [comment]
Yes of course, but I doesn't understand how to place types in one file or at least in one another folder.
